### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by adamzerella** [sehrope/node-rand-token#14]
I've submitted TypeScript definitions to the DT project, just wanted to check that @sehrope is cool with this?

PR in question: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43147

**Comment by sehrope** [comment]
Nice but rather than have it be separate in @types, let's add it to the module directly via a `"types"` entry in package.json. Better for the long term to keep things in sync.

Open it up as a PR to this repo and I'll take a look this week.

**Comment by sehrope** [comment]
Published to npm with type definitions a v1.0.1 :tada:
