### ISSUE TITLE
changelog?

### ISSUE THREAD

**Issue by diegohaz** [sehrope/node-rand-token#6]
I want to update it on my projects, but not sure what changed since the 2014 version nor if it is a breaking change.

I can investigate the commits (and I will), but a small changelog would be nice. 👍

**Comment by sehrope** [comment]
Would be a good idea going forward.

The latest change don't have any semver breakage. Most were to the dev dependencies or test setup (Travis config). The only code change was falling back to crypto.randomBytes if crypto.pseudoRandomBytes is not available as it disappeared for a bit in node v7 but now it's back so in theory the change wasn't even needed anyway.
